/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as ServiceAreasIndexRouteImport } from './routes/service-areas.index'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as ServiceAreasSlugRouteImport } from './routes/service-areas.$slug'
import { Route as ServicesSlugIndexRouteImport } from './routes/services.$slug.index'
import { Route as ServicesSlugCityRouteImport } from './routes/services.$slug.$city'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasIndexRoute = ServiceAreasIndexRouteImport.update({
  id: '/service-areas/',
  path: '/service-areas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServiceAreasSlugRoute = ServiceAreasSlugRouteImport.update({
  id: '/service-areas/$slug',
  path: '/service-areas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesSlugIndexRoute = ServicesSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesSlugRoute,
} as any)
const ServicesSlugCityRoute = ServicesSlugCityRouteImport.update({
  id: '/$city',
  path: '/$city',
  getParentRoute: () => ServicesSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/$slug': typeof ServicesSlugRouteWithChildren
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$slug/$city': typeof ServicesSlugCityRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/service-areas': typeof ServiceAreasIndexRoute
  '/services': typeof ServicesIndexRoute
  '/services/$slug/$city': typeof ServicesSlugCityRoute
  '/services/$slug': typeof ServicesSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/service-areas/$slug': typeof ServiceAreasSlugRoute
  '/services/$slug': typeof ServicesSlugRouteWithChildren
  '/service-areas/': typeof ServiceAreasIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/services/$slug/$city': typeof ServicesSlugCityRoute
  '/services/$slug/': typeof ServicesSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/llms.txt'
    | '/projects'
    | '/sitemap.xml'
    | '/service-areas/$slug'
    | '/services/$slug'
    | '/service-areas/'
    | '/services/'
    | '/services/$slug/$city'
    | '/services/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/llms.txt'
    | '/projects'
    | '/sitemap.xml'
    | '/service-areas/$slug'
    | '/service-areas'
    | '/services'
    | '/services/$slug/$city'
    | '/services/$slug'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/llms.txt'
    | '/projects'
    | '/sitemap.xml'
    | '/service-areas/$slug'
    | '/services/$slug'
    | '/service-areas/'
    | '/services/'
    | '/services/$slug/$city'
    | '/services/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ServiceAreasSlugRoute: typeof ServiceAreasSlugRoute
  ServicesSlugRoute: typeof ServicesSlugRouteWithChildren
  ServiceAreasIndexRoute: typeof ServiceAreasIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/': {
      id: '/service-areas/'
      path: '/service-areas'
      fullPath: '/service-areas/'
      preLoaderRoute: typeof ServiceAreasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/service-areas/$slug': {
      id: '/service-areas/$slug'
      path: '/service-areas/$slug'
      fullPath: '/service-areas/$slug'
      preLoaderRoute: typeof ServiceAreasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$slug/': {
      id: '/services/$slug/'
      path: '/'
      fullPath: '/services/$slug/'
      preLoaderRoute: typeof ServicesSlugIndexRouteImport
      parentRoute: typeof ServicesSlugRoute
    }
    '/services/$slug/$city': {
      id: '/services/$slug/$city'
      path: '/$city'
      fullPath: '/services/$slug/$city'
      preLoaderRoute: typeof ServicesSlugCityRouteImport
      parentRoute: typeof ServicesSlugRoute
    }
  }
}

interface ServicesSlugRouteChildren {
  ServicesSlugCityRoute: typeof ServicesSlugCityRoute
  ServicesSlugIndexRoute: typeof ServicesSlugIndexRoute
}

const ServicesSlugRouteChildren: ServicesSlugRouteChildren = {
  ServicesSlugCityRoute: ServicesSlugCityRoute,
  ServicesSlugIndexRoute: ServicesSlugIndexRoute,
}

const ServicesSlugRouteWithChildren = ServicesSlugRoute._addFileChildren(
  ServicesSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ServiceAreasSlugRoute: ServiceAreasSlugRoute,
  ServicesSlugRoute: ServicesSlugRouteWithChildren,
  ServiceAreasIndexRoute: ServiceAreasIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
